### ISSUE TITLE
Not working on ubuntu 22.04

### ISSUE THREAD

**Issue by Jaionfire** [cc20110101/onvif#1]
g++ -o test main.cpp -L./lib -lonvif -lssl -lcrypto -I./include -std=c++17
/usr/bin/ld: warning: libssl.so.10, needed by ./lib/libonvif.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.10, needed by ./lib/libonvif.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `RAND_status@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_CIPHER_CTX_set_padding@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_load_error_strings@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_get1_session@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_SealFinal@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_STORE_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_EncryptUpdate@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_use_PrivateKey_file@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_get_peer_certificate@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `ERR_clear_error@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_aes_128_gcm@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_library_init@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `sk_pop_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `CRYPTO_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `PEM_read_X509@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_des_ede3_cbc@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_set_default_passwd_cb_userdata@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `HMAC_CTX_init@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_set_default_verify_paths@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `RSA_generate_key@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_use_certificate_chain_file@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_CIPHER_CTX_init@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `OPENSSL_add_all_algorithms_noconf@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509V3_conf_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_EncryptFinal@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `DH_generate_parameters@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `RAND_load_file@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_STORE_CTX_get_error@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_NAME_oneline@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_connect@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `RSA_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_sha384@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_sha224@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_NAME_ENTRY_get_data@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_aes_256_cbc@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_STORE_CTX_set_error@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_DecryptUpdate@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `ERR_error_string@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_clear@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `d2i_X509@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_STORE_set_flags@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_STORE_load_locations@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_new@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_DecryptFinal@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_verify_cert_error_string@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_want@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `ERR_get_error@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_load_client_CA_file@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_set_default_passwd_cb@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `ERR_remove_state@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_ctrl@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_get_verify_result@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_load_crl_file@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `HMAC_CTX_cleanup@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_free@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_CIPHER_CTX_rand_key@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_shutdown@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_OpenFinal@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_EncryptInit_ex@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `RAND_pseudo_bytes@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_CIPHER_CTX_key_length@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_MD_CTX_cleanup@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_STORE_CTX_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_sha256@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_get_subject_name@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_sha512@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `BIO_new_socket@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `i2d_X509@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_aes_192_cbc@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `sk_num@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_peek@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_CIPHER_CTX_ctrl@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `ERR_error_string_n@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_state@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_SignFinal@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `HMAC_Update@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_md5@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `DH_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_OpenInit@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_set_verify@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_set_verify_depth@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_write@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_SESSION_free@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_VerifyFinal@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_STORE_CTX_new@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_PKEY_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_NAME_get_entry@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_NAME_get_index_by_NID@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_ctrl@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `HMAC_Init@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `BIO_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_CIPHER_block_size@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_CIPHER_CTX_cleanup@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_new@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_verify_cert@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_aes_128_cbc@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_set_client_CA_list@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_STORE_new@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `HMAC_Final@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `BIO_new_file@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_aes_192_gcm@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_STORE_CTX_init@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `sk_value@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `BIO_read@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSLv23_method@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_aes_256_gcm@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `RAND_seed@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `ERR_peek_error@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_DigestInit@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_DigestUpdate@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_get_pubkey@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_sha1@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_MD_CTX_init@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_set_bio@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_PKEY_encrypt_old@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_get_ext_d2i@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_LOOKUP_file@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `DH_check@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `PEM_read_bio_DHparams@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `GENERAL_NAME_free@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_free@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_load_verify_locations@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_set_session@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_PKEY_size@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_get_cert_store@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_read@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `X509_STORE_add_lookup@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_accept@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_CTX_set_session_id_context@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_DecryptInit_ex@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_DigestFinal_ex@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `BIO_write@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `ASN1_STRING_to_UTF8@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `i2v_GENERAL_NAMES@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `EVP_CIPHER_iv_length@libcrypto.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `SSL_get_error@libssl.so.10'
/usr/bin/ld: ./lib/libonvif.so: undefined reference to `ASN1_STRING_data@libcrypto.so.10'
collect2: error: ld returned 1 exit status

libonvif.so for old version of ssl and cryto , old ssl versions not supporting in ubuntu 22.04

old version:1.0
new version:3.0
how to slove it can you help on this?

**Comment by cc20110101** [comment]
The Docker container used to start the service at that time was not compatible with Ubuntu 22.
The gSAP tool used in the code repository is generated based on the official WSDL file
